### ISSUE TITLE
Upper formats as html-specialchars

### ISSUE THREAD

**Issue by scansec** [twigphp/Twig#1580] opened 2014-12-09 20:44 UTC
When using |upper on a variable, "DÆK OG FÆLGE" is showen as "D&AELIG;K OG F&AELIG;LGE"

When not using filers, or using capatilize it works fine.

using twig/twig (v1.16.2)

**Comment by stof** [comment] 2015-01-18 15:06
The issue seems to be that you apply the upper filter *after* escaping the HTML, which makes the HTML entity uppercased, thus breaking it (or maybe it gets escaped a second time)

**Comment by fabpot** [comment] 2015-01-25 12:17
@scansec Can you confirm @stof intuition?

**Comment by scansec** [comment] 2015-01-25 16:16
@fabpot , no, due to that it works using the filter capatilize, but not when using the filter uppercase.

**Comment by ninsuo** [comment] 2015-01-25 16:28
Your original string is `d&aelig;k og f&aelig;lge` and not `dæk og fælge` as you may see in your browser, because your browser interprets the `&aelig;` symbol to `æ`. The uppercase value for `&aelig;` is `&AElig;` and not `&AELIG;`, so if you're applying uppercase filter on the whole string, you're breaking those HTML entities.

Capitalize filter only put the first string's character to uppercase, so entities are not affected and you do not see any issue.

**Comment by fabpot** [comment] 2015-03-06 07:36
Closing as there is no feedback. @scansec Feel free to reopen with a reproducible test case if you still have the problem. Thanks.

**Closed by fabpot** 2015-03-06 07:36 UTC

**Comment by dommmel** [comment] 2017-09-06 10:11
Here's your test case:

https://twigfiddle.com/93xg4u

**Comment by xabbuh** [comment] 2017-09-06 10:34
@dommel You need to apply the  `raw` filter after the `upper` filter: https://twigfiddle.com/93xg4u/2

**Comment by dommmel** [comment] 2017-09-06 10:36
I see @xabbuh, thanks!
