### ISSUE TITLE
Blocks and {{ yield() }}

### ISSUE THREAD

**Issue by srsgores** [twigphp/Twig#1858] opened 2015-09-29 20:34 UTC
This is really a question: I'm looking for a way to *yield* from within a macro.

Something like macros for ``tab_item``, ``form_container``, and so forth might be good candidates for this.  It's not far from what's [described in the documentation](http://twig.sensiolabs.org/pdf/Twig.pdf) (Listing 22-5) with ``wrapped_input``.  Except in this case, it seems to me counter-intuitive to have a variant of a macro with 1 macro "passed-in" via ``self``, rather than creating a macro which supports a ``yield`` functionality.

I'm, of course, coming from handlebars, which has such a feature: ``{{yield}}``.

For example, in twig:

```
{% macro definition_item(term, definition) %}
	{% if term and definition %}
		<dt>
			{{ term }}
		</dt>
		<dd>
			{{ definition }}
		</dd>
	{% endif %}
        {{ yield() }}
{% endmacro %}
```

Where ``{{ yield() }}`` *yields* any values used when the macro is used in **block** form:

```
{{definition_item}}
    <dt>More content</dt>
    <dd>More content goes here</dd>
{{/definition_item}}
```

I would welcome any ideas on how to proceed.  Thanks in advance.

**Comment by hason** [comment] 2015-10-05 08:24
It's duplicate of #1175.

**Closed** 2015-10-05 10:12 UTC

**Comment by srsgores** [comment] 2015-10-05 15:02
@hason, can you provide an example of what a macro might look like, which accepts any content?  My understanding of [embed](http://twig.sensiolabs.org/doc/tags/embed.html) suggests that this may not be possible, as you must pass in the name of the template you wish to include...

**Comment by srsgores** [comment] 2015-10-05 15:09
Oh, I think I see: so I just create a ``content`` block within ever one of my macros...?
