### ISSUE TITLE
Twig_Node_Set hard coded into twig/lib/Twig/Parser.php

### ISSUE THREAD

**Issue by ken-spencer** [twigphp/Twig#2073] opened 2016-07-02 23:18 UTC
I am writing an extension that behaves similarly to the set tag, but is defining some internal features. However unlike set my extension gets a fatal error: "A template that extends another one cannot have a body in"

After debugging, I traced this problem to the following section in Parser.php. It appears that the workaround for this error for set is hardcoded in: 

	// bypass "set" nodes as they "capture" the output
        if ($node instanceof Twig_Node_Set) {
            return $node;
        }

Can we change this so that any tag can have this capability, not just set?

**Comment by stof** [comment] 2016-07-08 14:03
Duplicate of #2045

**Comment by fabpot** [comment] 2016-07-09 05:46
Closing as a duplicate

**Closed by fabpot** 2016-07-09 05:46 UTC
