### ISSUE TITLE
[PHP 8.1] During inheritance of JsonSerializable: Uncaught Declaration of Twig\Markup::jsonSerialize() should be compatible with JsonSerializable::jsonSerialize(): mixed

### ISSUE THREAD

**Issue by williamdes** [twigphp/Twig#3534] opened 2021-06-02 19:38 UTC
`twig/twig/src/Markup.php:43`

Error: [on PHP 8.1 CI](https://github.com/phpmyadmin/phpmyadmin/runs/2730389628#step:9:22)
```
PHP Fatal error:  During inheritance of JsonSerializable: Uncaught Declaration of Twig\Markup::jsonSerialize() should be compatible with JsonSerializable::jsonSerialize(): mixed

/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Markup.php:43
/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Markup.php:19
/home/runner/work/phpmyadmin/phpmyadmin/tmp/twig/fb/fb1a0d2016c3fc6c9ab5b48d37a6ffd92cd99f658bbb5f157d9ccefa203590e0.php:59
/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Template.php:394
/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Template.php:367
/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Template.php:379
/home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/TemplateWrapper.php:40
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Template.php:157
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Header.php:721
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Header.php:194
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Header.php:143
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Response.php:184
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Response.php:215
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Config/PageSettings.php:161
/home/runner/work/phpmyadmin/phpmyadmin/libraries/classes/Config/PageSettings.php:90
/home/runner/work/phpmyadmin/phpmyadmin/test/classes/Config/PageSettingsTest.php:48
/home/runner/work/phpmyadmin/phpmyadmin/vendor/phpunit/phpunit/phpunit:61
 in /home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Markup.php on line 19
```

**Comment by stof** [comment] 2021-06-03 13:45
this looks like a BC break in PHP 8.1 /cc @nikic

**Comment by nikic** [comment] 2021-06-03 14:43
This is due to https://wiki.php.net/rfc/internal_method_return_types. You can suppress the message by adding a `#[ReturnTypeWillChange]` attribute, assuming that you can't change the type right now (mixed in PHP 8.0).

Edit: Actually, you can specify a more specific type than mixed (most likely `array` here) on earlier versions. Assuming you don't have any BC commitments on your own for this method.

**Comment by stof** [comment] 2021-06-04 07:41
@nikic but why is this a fatal error and not a deprecation warning ?

**Comment by MauricioFauth** [comment] 2021-06-11 20:15
> but why is this a fatal error and not a deprecation warning ?

@stof This is caused by [PHPUnit's `convertDeprecationsToExceptions="true"` configuration](https://phpunit.readthedocs.io/en/9.5/configuration.html#the-convertdeprecationstoexceptions-attribute).

With `convertDeprecationsToExceptions="false"` it triggers a deprecation message:
```
PHP Deprecated:  Declaration of Twig\Markup::jsonSerialize() should be compatible with JsonSerializable::jsonSerialize(): mixed in /home/runner/work/phpmyadmin/phpmyadmin/vendor/twig/twig/src/Markup.php on line 43
```

**Comment by MauricioFauth** [comment] 2021-06-11 21:46
Fixed by https://github.com/twigphp/Twig/pull/3536.

**Closed as completed** 2021-06-14 07:28 UTC
