### ISSUE TITLE
 [ErrorException] Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by bohdanmoshchenko** [twigphp/Twig#4025] opened 2024-04-17 11:28 UTC
After update from 3.8 to 3.9.1 I have a bug after run **bin/console lint:twig ./templates/ --show-deprecations -vvv** command:
```
[ErrorException]                                              
  Warning: Trying to access array offset on value of type null
Exception trace:
  at /app/app/vendor/twig/twig/src/Lexer.php:181
 Twig\Lexer->tokenize() at /app/app/vendor/twig/twig/src/Environment.php:497
 Twig\Environment->tokenize() at /app/app/vendor/symfony/twig-bridge/Command/LintCommand.php:163
 Symfony\Bridge\Twig\Command\LintCommand->validate() at /app/app/vendor/symfony/twig-bridge/Command/LintCommand.php:139
 Symfony\Bridge\Twig\Command\LintCommand->getFilesInfo() at /app/app/vendor/symfony/twig-bridge/Command/LintCommand.php:124
 Symfony\Bridge\Twig\Command\LintCommand->execute() at /app/app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /app/app/vendor/symfony/console/Application.php:1096
 Symfony\Component\Console\Application->doRunCommand() at /app/app/vendor/symfony/framework-bundle/Console/Application.php:126
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /app/app/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /app/app/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /app/app/vendor/autoload_runtime.php:29
 require_once() at /app/app/bin/console:15
```

**Comment by xabbuh** [comment] 2024-04-17 11:51
Please provide an example template that triggers this error.

**Comment by bohdanmoshchenko** [comment] 2024-04-17 12:01
@xabbuh There are too many templates. I don`t know which one triggered this error.

**Comment by stof** [comment] 2024-04-17 12:09
the only array access in line 181 of the Lexer is `$this->regexes['lex_tokens_start']`, and I don't see how `$this->regexes` could be `null` at this point as `initialize()` is initializing the property.

**Comment by stof** [comment] 2024-04-17 12:10
and this code has not changed between 3.8 and 3.9.1

**Comment by bohdanmoshchenko** [comment] 2024-04-17 13:37
@stof After I downgraded to 3.8, which was earlier, the error disappeared.

**Comment by fabpot** [comment] 2024-04-17 14:18
@bohdanmoshchenko We would need a reproducer to better understand what's going on here.

**Comment by Atesca** [comment] 2024-04-17 14:42
To reproduce create a file with the content `{% extends 'base.html.twig' %}` in the templates folder.

Running the lint command `bin/console lint:twig templates --show-deprecations` against that results in:

ERROR  in templates/firstFile.html.twig (line 0)
  >> The "Symfony\Bridge\Twig\NodeVisitor\TranslationNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since 3.9 (to be removed in 4.0). 
                                                                                                                        
 [WARNING] 0 Twig files have valid syntax and 1 contain errors. 

Add a second file `secondFile.html.twig` with the same content and run the command again results in
In Lexer.php line 181:
                                                                
  Warning: Trying to access array offset on value of type null

**Comment by JohJohan** [comment] 2024-04-18 08:44
I can confirm we have the same thing, after upgrading to 3.9.0 it already breaks btw.

**Comment by gjuric** [comment] 2024-04-18 09:58
Same here, the exception trace is 

```bin/console lint:twig --env=test templates --show-deprecations -vvv

In Lexer.php line 181:

  [ErrorException]
  Warning: Trying to access array offset on value of type null


Exception trace:
  at vendor/twig/twig/src/Lexer.php:181
 Twig\Lexer->tokenize() at vendor/twig/twig/src/Environment.php:497
 Twig\Environment->tokenize() at vendor/symfony/twig-bridge/Command/LintCommand.php:160
 Symfony\Bridge\Twig\Command\LintCommand->validate() at vendor/symfony/twig-bridge/Command/LintCommand.php:136
 Symfony\Bridge\Twig\Command\LintCommand->getFilesInfo() at vendor/symfony/twig-bridge/Command/LintCommand.php:121
 Symfony\Bridge\Twig\Command\LintCommand->execute() at vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:1049
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/framework-bundle/Console/Application.php:125
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at vendor/symfony/framework-bundle/Console/Application.php:79
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at vendor/autoload_runtime.php:29
 require_once() at bin/console:10
```

I've dumped the `Twig\Source` object that causes the error when passed to `$this->lexer->tokenize($source)`

```
Twig\Source Object
(
    [code:Twig\Source:private] => {% extends 'knp_menu_base.html.twig' %}

{% macro attributes(attributes) %}
    {%- for name, value in attributes %}
    {%- if value is not none and value is not same as(false) -%}
        {{- ' %s="%s"'|format(name, value is same as(true) ? name|e : value|e)|raw -}}
    {%- endif -%}
{%- endfor -%}
{% endmacro %}

{% block compressed_root %}
{% apply spaceless %}
{{ block('root') }}
{% endapply %}
{% endblock %}

{% block root %}
{% set listAttributes = item.childrenAttributes %}
{{ block('list') -}}
{% endblock %}

{% block list %}
    {%- if item.hasChildren and options.depth is not same as(0) and item.displayChildren -%}
        {%- import _self as knp_menu -%}
        {{ block('children') }}
    {%- endif -%}
{% endblock %}

{% block children %}
{# save current variables #}
{% set currentOptions = options %}
{% set currentItem = item %}
{# update the depth for children #}
{% if options.depth is not none %}
    {%- set options = currentOptions|merge({'depth': currentOptions.depth - 1}) -%}
{% endif %}
{% for item in currentItem.children %}
    {{ block('item') }}
{% endfor %}
{# restore current variables #}
{% set item = currentItem %}
{% set options = currentOptions %}
{% endblock %}

{%- block item -%}
    {%- if item.displayed -%}
{# building the class of the item #}
        {%- set classes = item.attribute('class') is not empty ? [item.attribute('class')] : ['member-menu__item'] -%}
        {%- if matcher.isCurrent(item) -%}
            {%- set classes = classes|merge(['member-menu__item--selected']) -%}
        {%- elseif matcher.isAncestor(item) -%}
            {%- set classes = classes|merge([options.ancestorClass]) -%}
        {%- endif -%}
        {%- if item.actsLikeFirst -%}
{#            {%- set classes = classes|merge([options.firstClass]) -%}#}
        {%- endif -%}
        {%- if item.actsLikeLast -%}
{#            {%- set classes = classes|merge([options.lastClass]) -%}#}
        {%- endif -%}
        {%- set attributes = item.attributes -%}
        {%- if classes is not empty -%}
            {%- set attributes = attributes|merge({'class': classes|join(' ')}) -%}
        {%- endif -%}
{# displaying the item #}
        {%- import _self as knp_menu -%}
        <a{{- knp_menu.attributes(attributes) -}}
            {%- if item.uri is not empty and (not matcher.isCurrent(item) or options.currentAsLink) -%}
                {{- block('linkElement') -}}
            {%- else -%}
                {{- block('spanElement') -}}
            {%- endif -%}
{# render the list of children#}
            {%- set childrenClasses = item.childrenAttribute('class') is not empty ? [item.childrenAttribute('class')] : [] -%}
            {%- set childrenClasses = childrenClasses|merge(['menu_level_' ~ item.level]) -%}
            {%- set listAttributes = item.childrenAttributes|merge({'class': childrenClasses|join(' ') }) -%}
            {{- block('list') -}}
        </a>
    {%- endif -%}
{%- endblock -%}

{% block linkElement %}{% import _self as knp_menu %} href="{{ item.uri }}{{ item.getExtra('anchor') }}"{{ knp_menu.attributes(item.linkAttributes) }}>{{ block('label') }}{% endblock %}

{% block spanElement %}{% import _self as knp_menu %}<span{{ knp_menu.attributes(item.labelAttributes) }}>{{ block('label') }}</span>{% endblock %}

{% block label %}{{ item.label|trans(item.getExtra('translation_params', {}), item.getExtra('translation_domain', 'menu')) }}{% endblock %}

    [name:Twig\Source:private] => templates/menu.html.twig
    [path:Twig\Source:private] =>
)
```

**Comment by xabbuh** [comment] 2024-04-18 11:45
will probably be fixed by #4038

**Closed as completed** 2024-04-18 11:52 UTC

**Comment by trsteel88** [comment] 2024-04-21 23:12
I am still getting the same error as @atesca09 on 3.9.3

**Comment by xabbuh** [comment] 2024-04-22 06:51
@trsteel88 Can you please open a new issue and provide a small example application that allows to reproduce it?

**Comment by lugosium** [comment] 2024-04-23 13:47
> I am still getting the same error as @atesca09 on 3.9.3

Same here, looking for a reproducer.

**Comment by trsteel88** [comment] 2024-04-29 00:10
@xabbuh it occurs on the default install of Symfony: https://github.com/trsteel88/Broken-Twig/actions/runs/8871380718/job/24354277478

The project was created with `symfony new --webapp my_project`
