### ISSUE TITLE
* unexpected in eval() function error 

### ISSUE THREAD

**Issue by kletellier** [twigphp/Twig#1816] opened 2015-09-11 15:16 UTC
After commit 7cb4b94

An error crash all my template rendering (with or without caching). In compiled template we can see it's an commenting mistake (missing /* at start of templating source adding at bottom of cached template)

Here is an example :  
```php
<?php

/* index.html.twig */
class __TwigTemplate_7132f697a851e9fa2ec4276e332429243764f64c83f43c2a321f955b75e91820 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        // line 1
        $this->parent = $this->loadTemplate("layoutb.html.twig", "index.html.twig", 1);
        $this->blocks = array(
            'titre' => array($this, 'block_titre'),
            'jscript' => array($this, 'block_jscript'),
            'contenu' => array($this, 'block_contenu'),
        );
    }

    protected function doGetParent(array $context)
    {
        return "layoutb.html.twig";
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_titre($context, array $blocks = array())
    {
        echo "Bienvenue";
    }

    // line 5
    public function block_jscript($context, array $blocks = array())
    {
        // line 6
        echo "    

  ";
    }

    // line 10
    public function block_contenu($context, array $blocks = array())
    {
        // line 11
        echo "    <div class=\"container\">
      <div class=\"row\">
        &nbsp;
      </div>
      
  </div>
";
    }

    public function getTemplateName()
    {
        return "index.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  48 => 11,  45 => 10,  39 => 6,  36 => 5,  30 => 3,  11 => 1,);
    }
}
/* {% extends "layoutb.html.twig" %}*/*/
/* /* */*/
/* /* {% block titre %}Bienvenue{% endblock %}*/*/
/* /* */*/
/* /*   {% block jscript %}*/*/
/* /*     */*/
/* /* */*/
/* /*   {% endblock %} */*/
/* /* */*/
/* /*   {% block contenu %}*/*/
/* /*     <div class="container">*/*/
/* /*       <div class="row">*/*/
/* /*         &nbsp;*/*/
/* /*       </div>*/*/
/* /*       */*/
/* /*   </div>*/*/
/* /* {% endblock %}*/
```

**Comment by nicolas-grekas** [comment] 2015-09-11 15:34
Thanks for the issue :) What is the source code of the template ?

**Comment by ninsuo** [comment] 2015-09-11 15:36
Can't reproduce this on latest Twig 1.x: http://twigfiddle.com/eh6fhb

**Comment by nicolas-grekas** [comment] 2015-09-11 15:40
I don't understand the double `/* ` at the beginning of each line.
I tried https://3v4l.org/6FMY3 but this is working well.

**Comment by nicolas-grekas** [comment] 2015-09-11 15:41
@kletellier can you please run the tests suite and see if it fails or not?

**Comment by kcivey** [comment] 2015-09-11 15:43
We're getting this too. Had to revert to the Twig version we had before (which I had to specify with a commit hash since this change didn't even come with a patch version bump).

**Comment by nicolas-grekas** [comment] 2015-09-11 15:44
Reproduced! The issue is on Windows with CR+LF!
https://3v4l.org/Lf3iW

**Comment by kcivey** [comment] 2015-09-11 15:47
Hmm, no Windows involved in ours. It's all Ubuntu. Unless somehow some CRLFs slipped into the templates. Oh, actually that may have happened since some template content was submitted from textareas in HTML forms originally.

**Comment by nicolas-grekas** [comment] 2015-09-11 15:52
Fixed in #1817

**Closed** 2015-09-11 15:58 UTC

**Comment by kcivey** [comment] 2015-09-11 16:07
Thanks! That seems to have done it.

**Comment by stof** [comment] 2015-09-11 20:49
> We're getting this too. Had to revert to the Twig version we had before (which I had to specify with a commit hash since this change didn't even come with a patch version bump).

This change has not yet been released at all. So using the stable version of Twig would have fixed it too rather than specifying a commit hash.

**Comment by kcivey** [comment] 2015-09-11 20:59
True. Sorry for the inappropriate complaint.
