### ISSUE TITLE
Local function support

### ISSUE THREAD

**Issue by Bilge** [twigphp/Twig#2625] opened 2018-02-07 16:10 UTC
If one wants to quickly write a local function for just the current template, one must use macros, because there are no other options. However, macros must be imported, which requires a redundant `import` tag and also isolates the macro from the calling context, meaning the caller has to pass everything manually. In this case, we must pass the local context to the local macro, which also seems completely redundant.

There should be a way to create a local function or macro, either by extending the feature set of macros or adding a new type of tag, which would create a local template function that has access to the calling scope. This new tag, or modified macro would differ from the current macro implementation in that:

1. It is immediately available to the current template without requiring an `import` tag.
2. It has access to the current template's context automatically.
3. If a template using such a function is included, the function will be correctly evaluated in the context of the template which defines it, but the function itself cannot be imported and used by other templates (because it's a local function only).

**Comment by fabpot** [comment] 2019-05-17 11:11
I don't think we need another way of creating a way to abstract a piece of template. We already have plenty of them. I understand that having to import "local" macros manually is annoying. But I think that if macros were available automatically in the current template, that would go a long way. So, closing as a duplicate of #861.

**Closed as completed by fabpot** 2019-05-17 11:11 UTC
Labels: Macros
