### ISSUE TITLE
Feature Request: Allow nested comments. Suggestion: `{##`

### ISSUE THREAD

**Issue by ThomasLandauer** [twigphp/Twig#2897] opened 2019-03-13 17:54 UTC
It would be nice to have a quick way to comment out some lines of code that already contain comments:
```twig
Line1 {# comment #}
Line2 {# comment #}
Line3 {# comment #}
Line4 {# comment #}
Line5 {# comment #}
```
One way to achieve this would be one-line comments (like PHP's `//`) - this has been suggested before, see https://github.com/twigphp/Twig/issues/1331

Another (more consistent with the existing Twig syntax) way would be to introduce "second-level" comments. What about `{##`? This could ignore `#}` and only get closed by `##}`.

There are IDE keyboard shortcuts available for this feature in PHP and YAML (by prepending `//` or `#` to each line). Just Twig is missing.

**Comment by ericmorand** [comment] 2019-06-17 11:59
It think this is simply a bug of the lexer. `{# {# #} #}` should be lexed to a comment token containing `{# #}` - and thus be ignored since the current lexer simply ignore comment tokens.

The same issue applies to the `verbatim `tag:

https://twigfiddle.com/a3nn16

**Comment by SpacePossum** [comment] 2019-06-17 12:10
it would be nice if these comments do not "eat up" the line break,
so 

```
test  {## foo ##}
bar
```

renders
```
test
bar
```

and not
```
test bar
```
https://twigfiddle.com/srb8mr

**Comment by stof** [comment] 2019-06-17 12:33
@ericmorand the whole point of comments and verbatim is that they are **not** lexing what is inside them. Changing that would be a big BC break.

And btw, the same is true for comments in all other languages I know about. PHP, JS, CSS, HTML all use the first closing marker for the comment for instance instance, and the list can go on with more languages.

**Comment by ericmorand** [comment] 2019-06-17 13:37
@stof , I agree totally. This is the way to go. As you say, this is how it works with other languages and this is how this should work with Twig too.

About verbatim, I think this is debatable. There is a real need to be able to display raw verbatim syntaxt inside a verbatim block. What do you think.

**Comment by 7ochem** [comment] 2019-09-30 10:14
If I comment out Twig lines in PhpStorm with <kbd>Ctrl</kbd>+<kbd>/</kbd>, then it takes existing comments into account:

```
    <div>{{ some_var }}</div>
    <div>{# comment #}{{ another_var }}</div>
```
<kbd>Ctrl</kbd>+<kbd>/</kbd> :arrow_down: 
```
{#    <div>{{ some_var }}</div>#}
{#    <div>#}{# comment #}{#{{ another_var }}</div>#}
```
Only bad thing is that it doesn't revert well:
Another <kbd>Ctrl</kbd>+<kbd>/</kbd> gives :arrow_down: 
```
    <div>{{ some_var }}</div>
    <div> comment {{ another_var }}</div>
```

**Comment by stof** [comment] 2019-09-30 13:02
> About verbatim, I think this is debatable. There is a real need to be able to display raw verbatim syntaxt inside a verbatim block. What do you think.

We cannot change verbatim to require nested verbatims to be balanced. That would be a BC break.

**Comment by fabpot** [comment] 2019-11-15 15:51
Anyone willing to give a try at implementing `{##`? If we find a simple way to implement it, I think it could be a good addition.

**Closed as completed** 2019-12-03 07:33 UTC

**Comment by smnandre** [comment] 2024-01-20 02:54
Hey @ThomasLandauer 

I started a tiny poc here: https://github.com/smnandre/Twig/tree/feat/comment-block 

```twig
{##
Anything there until the last line is commented
{{ foo }} {#
##} And this will be displayed
```

First use-cases look good, and (other) tests stay green.

(but i probably missed something as it seams a bit to "easy")

I'd be happy to discuss the expected behaviour before going further :) 

How would this work ? Do you have any edge-cases in mind ? Any special needs ?
