### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by Tomboman** [twigphp/Twig#1804] opened 2015-09-07 09:52 UTC
When I am using a code like this:

{{ example.otherName|raw }}

And this var doesn't exists.  I will get a notice:
Notice: Array to string conversion in C:\xampp\htdocs\httpdocs\Twig-1.18.0\lib\Twig\Environment.php(332) : eval()'d code on line 186
I tried upgrading to a new version, but this doesn't solve the problem

**Comment by Tobion** [comment] 2015-09-07 12:00
I rather think that example.otherName is an array. Thus you get this error: http://twigfiddle.com/gn3j45
Otherwise please provide a failing test case.

**Comment by fabpot** [comment] 2015-09-09 05:20
Closing as there is no feedback. @Tomboman Don't hesitate to open it again with a reproducible test case.

**Closed by fabpot** 2015-09-09 05:20 UTC

**Comment by Tomboman** [comment] 2015-09-09 14:06
Yes, it is an array.
However, I expect a twig error, or simply, it won't show anything.
But instead, it shows a PHP error.

**Comment by Tobion** [comment] 2015-09-09 15:04
Why would you expect something else? It's still PHP. And changing that is not possible as this is the PHP behavior that templates are compiled to. Wrapping that with something else would cause huge overhead as it would need to be caught for every single output.

**Comment by stof** [comment] 2015-09-09 15:29
Btw, if you really want to add such huge overhead, it is possible to write a Twig extension wrapping all printed expressions in a safeguard thanks to a node visitor. Twig is flexible enough to do this.
Wrapping all places which could perform a string casting would be much harder (the hard part being to identify all these cases) but still possible for most of them.

But I don't plan to spend time on implementing such extension, as I don't plan to use it because of the overhead.

And if you want a better error than a PHP notice, you can register an error handler turning notices into exceptions (Symfony does it in dev mode for instance, and most other frameworks also do it as it makes debugging much easier).
If you get exceptions for notices, the normal Twig error handling will add the location of the error in the message too.

**Comment by joelpittet** [comment] 2015-09-10 00:48
@Tomboman  In Drupal 8 we do this because we have a legacy API of "renderable arrays".  So if you need an example of how to do this you can check it out what @stof mentioned.
