### ISSUE TITLE
Front matter support

### ISSUE THREAD

**Issue by jkufner** [twigphp/Twig#2440] opened 2017-04-07 11:34 UTC
Front Matter is an elegant way to store metadata in "text" documents. It is widely used by static website generators, but it may be useful for other applications too. Content management systems may use template metadata to provide user with some description what given layout/theme does — for example Drupal themes have info.yml file.

## The proposal

 Add front matter support to Twig template parser, then provide the metadata via `Template::getMetadata()` method. That's all.

Optional feature: Provide current front matter metadata in some variable. Question is how exactly deal with extended templates — `array_merge_recursive` may be a good way.

### YAML template example

```.twig
---
title: Hello world
menu: main
weight: 20
---
{% extend layout.html.twig %}
{% block content %}
Hello world!
{% endblock %}
```

### JSON template example

```.twig
{{{
  "title": "Hello world",
  "menu": "main",
  "weight": 20
}}}
{% extend layout.html.twig %}
{% block content %}
Hello world!
{% endblock %}
```

## Backwards compatibility

Twig templates usually don't start with a line of `---` or `{{{`, therefore, this feature should not break anything in most situations.

YAML style `---` could theoretically break stuff and it requires a library to parse YAML anyway, so it has to be disabled by default.

JSON style `{{{` … `}}}` is a subset of Twig's `{{ var }}` syntax, so it is backwards compatible.

## Dependencies

- JSON front matter can be implemented using standard `json_parse`.
- YAML library should be optional dependency.

## Extensions ­– Custom front matters

Twig may allow registering a custom front matter parser. The front matter parser needs to know begin line, end line, and a parsing function.

### Pseudo-example for JSON front matter

```.php
class CustomFrontMatter extends Twig_Extension {
    public function getFrontMatters() {
        return [
            [ "{{{", "}}}", 'json_parse' ]
        ];
    }
}
```

## References

- https://www.drupal.org/docs/8/theming-drupal-8/defining-a-theme-with-an-infoyml-file
- https://jekyllrb.com/docs/frontmatter/
- https://gohugo.io/content/front-matter/
- https://hexo.io/docs/front-matter.html
- https://www.staticgen.com/

**Comment by stof** [comment] 2017-04-07 13:58
> Twig templates usually don't start with a line of --- or {{{, therefore, this feature should not break anything.

Twig templates can be used to output any textual content. Anything outside Twig markup is part of the template output. So this is a **huge** BC break.

**Comment by jkufner** [comment] 2017-04-07 14:32
You are right, I updated feature request description. The `{{{ … }}}` front matter should be ok since it matches existing `{{ … }}`.

**Comment by stof** [comment] 2017-04-07 14:36
@jkufner this is not good either, as it makes the syntax ambiguous. The ``{{{foo: bar}}}`` syntax means echoing a Twig hash (which will break at rendering time if you don't have some hook into Twig to transform it, as arrays are not castable to string without notice in PHP 5.4+, but this is still valid syntax and it is possible to write such hook).

the ``{{ }}`` syntax in Twig means ``echo``. It cannot be repurposed for something else.

**Comment by jkufner** [comment] 2017-04-07 15:26
@stof The front matter can be only the very first token in the file and the `{{{` must be on its own line, so the impact of this on any existing code would be very limited. So `"{{{ foo: bar }}}\n"` is the Twig hash, but `"{{{\n 
 foo: bar\n}}}\n"` is a front matter. At least this is how it works in most applications which use front matters.

**Comment by stof** [comment] 2017-04-07 15:29
but newlines are allowed inside Twig hashes. So this is a BC break

**Comment by julienfalque** [comment] 2017-04-07 15:33
IMO such feature does not belong to Twig core even with a BC implementation or an acceptable BC break.

**Comment by stof** [comment] 2017-04-07 15:36
Most tools using front matters actually don't expect the format parser to support their front matter. they remove the front matter from the source before giving it to the parser.

this would be much more sensible.

and it would keep it possible for people to use Twig to *output* a content containing a front matter btw (as long as you don't try to use it at the same time for the loading of the template and for the output of course, or it becomes crazy)

**Comment by fabpot** [comment] 2017-05-22 05:54
Closing as it was rejected in the past already. Twig is agnostic and such features can be implemented outside of Twig quite easily.

**Closed by fabpot** 2017-05-22 05:54 UTC

**Comment by hason** [comment] 2020-11-04 21:51
@jkufner It is possible to use https://github.com/webuni/front-matter#twig-loader

**Comment by localheinz** [comment] 2021-01-10 18:32
@hason 

The problem is that this only separates the front matter from the template's source code, but it does not allow rendering the template with context merged from the context passed to `Twig\Environment::render()` and the context parsed from the front matter.

I agree that this would be a very useful feature to have, even if it has been rejected multiple times in the past.

**Comment by hason** [comment] 2021-01-14 17:49
@localheinz It is possible to inject the front matter to the Twig template, see https://github.com/webuni/front-matter#twig-loader
