### ISSUE TITLE
Not compiling for PHP 7.0.4

### ISSUE THREAD

**Issue by jfha73** [twigphp/Twig#2006] opened 2016-03-24 19:10 UTC
Hey guys, I'm trying to compile your extension to use it with PHP 7 and all I'm getting is this:

`php-7.0.4/ext/twig/twig.c:23:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
compilation terminated.
Makefile:682: recipe for target 'ext/twig/twig.lo' failed
make: *** [ext/twig/twig.lo] Error 1
`

Any ideas how I can fix this so i can compile it?

Thanks.

**Comment by jfha73** [comment] 2016-03-24 19:17
Never mind, the file is called php_smart_string.h, so I changed the name but I'm getting this now:

`/home/jorge/Downloads/php-7.0.4/ext/twig/twig.c:1060:33: error: macro "ZVAL_STRING" passed 3 arguments, but takes just 2
   ZVAL_STRING(zmethod, method, 1);
                                 ^
/home/user/Downloads/php-7.0.4/ext/twig/twig.c:1060:3: error: ‘ZVAL_STRING’ undeclared (first use in this function)
   ZVAL_STRING(zmethod, method, 1);
`

and this:

`/home/user/Downloads/php-7.0.4/ext/twig/twig.c:661:116: error: macro "zend_unmangle_property_name" passed 4 arguments, but takes just 3
 e, pptr->name_length, (const char **) &class_name, (const char **) &prop_name);
                                                                              ^
/home/user/Downloads/php-7.0.4/ext/twig/twig.c:661:2: error: ‘zend_unmangle_property_name’ undeclared (first use in this function)
  zend_unmangle_property_name(pptr->name, pptr->name_length, (const char **) &cl
  ^
/home/user/Downloads/php-7.0.4/ext/twig/twig.c:666:50: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
  add_assoc_string(retval, prop_name, prop_name, 1);
                                                  ^
/home/user/Downloads/php-7.0.4/ext/twig/twig.c:666:2: error: ‘add_assoc_string’ undeclared (first use in this function)
  add_assoc_string(retval, prop_name, prop_name, 1);
`

and this:

`/home/user/Downloads/php-7.0.4/ext/twig/twig.c:640:2: error: too many arguments to function ‘add_assoc_stringl_ex’
  add_assoc_stringl_ex(retval, item, item_len+1, item, item_len, 0);
`

and this

`/home/user/Downloads/php-7.0.4/ext/twig/twig.c:632:7: error: too many arguments to function ‘zend_lookup_class’
   if (zend_lookup_class("Twig_Template", strlen("Twig_Template"), &twig_templat
       ^
`

and this

`/home/user/Downloads/php-7.0.4/ext/twig/twig.c:597:2: error: unknown type name ‘zend_uint’
  zend_uint class_name_len;
  ^
`

And many more like them.

**Comment by xabbuh** [comment] 2016-03-24 19:39
The extension was not ported to PHP 7 yet.

**Comment by Tobion** [comment] 2016-03-25 00:31
Duplicate of #1695

**Closed** 2016-03-25 11:12 UTC
