### ISSUE TITLE
1.18 breaks assetic dumps

### ISSUE THREAD

**Issue by Rhonun** [twigphp/Twig#1614] opened 2015-01-28 16:53 UTC
So we have an embed that includes some JS and some SASS. Something like this

    {% embed 'MyBundle:Form:baseForm.html.twig' %}
        {% block custom_css %}
            {{ parent() }}

            {% stylesheets filter='compass' output='bundles/mybundle/css/mysass.css'
            '@MyBundle/Resources/public/sass/mySass.scss' %}
                <link rel="stylesheet" href="{{ asset_url }}">
            {% endstylesheets %}

        {% endblock %}
        {% block below_main_panel %}
          <CONTENT HERE>
        {% endblock %}
        {% block custom_js %}
            {{ parent() }}

            {% javascripts output='bundles/mybundle/js/myForm.js'
            '@MyBundle/Resources/public/js/form.js' %}
                <script type="text/javascript" src="{{ asset_url }}"></script>
            {% endjavascripts %}
        {% endblock %}
    {% endembed %}

Since the 1.18 update the javascripts and stylesheets blocks are being ignored by php app/console assetic:dump

**Comment by fabpot** [comment] 2015-01-29 07:19
Can you confirm that #1616 fixes this issue?

**Comment by XWB** [comment] 2015-01-29 08:47
Dumping assets doesn't work with https://github.com/twigphp/Twig/pull/1616 though https://github.com/twigphp/Twig/issues/1611 seems to be fixed.

![image](https://cloud.githubusercontent.com/assets/1032281/5954743/c2d16884-a79b-11e4-94e9-e32cb6f13f38.png)

**Comment by XWB** [comment] 2015-02-02 14:16
@Rhonun Do you perhaps have LiipThemeBundle installed?

https://github.com/liip/LiipThemeBundle/issues/114

**Comment by Rhonun** [comment] 2015-02-02 20:30
I do not. When the javascripts and stylesheets declarations are outside of the embed they work. It's when they are inside of it that they don't

**Comment by fabpot** [comment] 2015-08-15 21:19
Closing as nobody reported the same problem in the last 6 months. Feel free to reopen if you can provide a small snippet that reproduces the problem.

**Closed by fabpot** 2015-08-15 21:19 UTC
