### ISSUE TITLE
Using --classmap-authoritative option for composer fails loading some Twig classes

### ISSUE THREAD

**Issue by GhaziTriki** [twigphp/Twig#2732] opened 2018-08-07 08:33 UTC
## Type

- Critical bug (Docker)

## Problem description

Using `--classmap-authoritative` option for composer fails loading Twig classes that contains `Test` word.

## Steps to reproduce

Run composer on a project using TWIG using `--classmap-authoritative` option.

## Expected behavior / Proposed solutions

No missing classes from the generated autoload.

**Comment by carakas** [comment] 2018-08-07 08:35
Can you add a little bit more info of the version of twig and the actual error?

**Comment by GhaziTriki** [comment] 2018-08-07 08:51
It happens when the ForkCMS `php bin/console assetic:dump .` command is ran. We have the following stacktrace.

```
In Core.php line 203:

  [Symfony\Component\Debug\Exception\ClassNotFoundException]
  Attempted to load class "Twig_Test" from the global namespace.
  Did you forget a "use" statement?


Exception trace:
 Twig_Extension_Core->getTests() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/ExtensionSet.php:451
 Twig_ExtensionSet->initExtension() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/ExtensionSet.php:431
 Twig_ExtensionSet->initExtensions() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/ExtensionSet.php:400
 Twig_ExtensionSet->getUnaryOperators() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/Environment.php:941
 Twig_Environment->getUnaryOperators() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/Lexer.php:356
 Twig_Lexer->getOperatorRegex() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/Lexer.php:65
 Twig_Lexer->__construct() at /var/www/raxbolt/vendor/twig/twig/lib/Twig/Environment.php:509
 Twig_Environment->tokenize() at /var/www/raxbolt/vendor/kriswallsmith/assetic/src/Assetic/Extension/Twig/TwigFormulaLoader.php:37
 Assetic\Extension\Twig\TwigFormulaLoader->load() at /var/www/raxbolt/vendor/kriswallsmith/assetic/src/Assetic/Factory/Loader/CachedFormulaLoader.php:59
 Assetic\Factory\Loader\CachedFormulaLoader->load() at /var/www/raxbolt/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:160
 Assetic\Factory\LazyAssetManager->load() at /var/www/raxbolt/vendor/kriswallsmith/assetic/src/Assetic/Factory/LazyAssetManager.php:195
 Assetic\Factory\LazyAssetManager->getNames() at /var/www/raxbolt/vendor/symfony/assetic-bundle/Command/DumpCommand.php:117
 Symfony\Bundle\AsseticBundle\Command\DumpCommand->execute() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/raxbolt/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/raxbolt/bin/console:54

assetic:dump [--forks FORKS] [--watch] [--force] [--period PERIOD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<write_to>]

Script php bin/console assetic:dump . handling the post-install-cmd event returned with error code 255
```

**Comment by stof** [comment] 2018-08-13 10:48
I think this is a bug of Composer, where it excludes any class containing `Test` in their name from the generated classmap.

**Comment by fabpot** [comment] 2019-01-12 02:04
Closing as it is apparently not a bug in Twig itself.

**Closed as completed by fabpot** 2019-01-12 02:04 UTC
