### ISSUE TITLE
Finding files in the templates folder

### ISSUE THREAD

**Issue by cakewalker** [twigphp/Twig#2190] opened 2016-10-18 15:05 UTC
Is it by design that Twig can find a templates folder that's a sibling folder of the folder containing the calling PHP file but can't find the templates files? I was tinkering with Twig for the first time (and with PHP for the first time in a long time!) so no doubt what I was coming up with isn't best practice, but I found the following doesn't work:

`$loader = new Twig_Loader_Filesystem('../templates');`
...
`$template = $twig->loadTemplate('index.html.twig');`

Twig doesn't throw an error saying it can't find the templates folder but does say it can't find the index.html.twig file - the error message has ../ stripped from the path. The templates folder seems to have to be a subfolder of the path that the PHP file is in, or an absolute path to the templates folder specified.

**Comment by stof** [comment] 2016-10-18 15:16
There is a regression in Twig for the case where the path used to configure ``Twig_Loader_Filesystem`` is a relative path (relative to the CWD).
The workaround is to pass an absolute path to the Twig_Loader_Filesystem constructor.

Btw, note that using relative path is fragile, because they are *not* relative to the file containing the code, but to the current working directory of the execution (which will be the folder containing the main PHP file for a web request, and the current working directory for CLI). And so the path being used may be different between execution.

**Comment by fabpot** [comment] 2016-10-19 22:26
Closing as a duplicate of #2145

**Closed by fabpot** 2016-10-19 22:26 UTC
