### ISSUE TITLE
Twig v1.22.2 ContextErrorException: Warning: filemtime(): stat failed for 

### ISSUE THREAD

**Issue by tuanquynh0508** [twigphp/Twig#1854] opened 2015-09-28 05:10 UTC
Hi !

I am using Symfony 2.3 with Twig 1.*, everything not working after I run "composer update". System error: 

ContextErrorException: Warning: filemtime(): stat failed for 
/home/nntuan/projects/dashboard/app/cache/dev_tuan/twig/7/1/71baaa9514a151dcfa15e2d0da9c1fa2c5ebb9718d44d3f294ef0e433986bbea.php in /home/nntuan/projects/dashboard/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 90

I not found file "71baaa9514a151dcfa15e2d0da9c1fa2c5ebb9718d44d3f294ef0e433986bbea.php" in folder: /home/nntuan/projects/dashboard/app/cache/dev_tuan/twig/7/1/

Help me please!.

**Comment by Tobion** [comment] 2015-09-28 15:21
Duplicate of #1848. Please use the search next time.

**Comment by tuanquynh0508** [comment] 2015-09-30 04:08
Thanks you!.

**Comment by Tobion** [comment] 2015-09-30 09:37
Please close this ticket then.

**Closed** 2015-09-30 09:49 UTC
