### ISSUE TITLE
[1.21.1][PHP7][Performance] Twig_NodeTraverser

### ISSUE THREAD

**Issue by hanikesn** [twigphp/Twig#1810] opened 2015-09-10 11:39 UTC
I'm currently in the progress in making our codebase ready for PHP7 and found a serious performance regression. Clearing the cache of our Symonfy application takes 8 times longer. I tried to track it down and found out that most time is spent in `Twig_NodeTraverser`. I added the following code to `\Twig_Parser::parse`:
```
PHP_Timer::start();
$node = $traverser->traverse($node);
self::$traverse += PHP_Timer::stop();
```
And here's my output:
```
$ time ~/misc/php/bin/php ./console cache:clear 
Clearing the cache for the dev environment with debug true
Traverse 2.4 minutes

real    2m41.792s
user    2m40.563s
sys     0m1.100s
$ time php ./console cache:clear 
Clearing the cache for the dev environment with debug true
Traverse 8.86 seconds

real    0m21.854s
user    0m21.103s
sys     0m0.710s
```

I guess this is a problem within PHP, but we need to start somewhere to track it down.

**Comment by sstok** [comment] 2015-09-11 07:24
The `Twig_NodeTraverser` hasn't changed much since 2014 so it's properly related to one or more NodeVisitors.

**Comment by fabpot** [comment] 2015-10-12 07:17
Are you saying that it takes 2.4 minutes for PHP 7 and 21 seconds for PHP 5.? for the exact same application? If yes, can you list the node visitors you have registered?

**Comment by hanikesn** [comment] 2015-10-12 10:08
Visitors:
```Twig_NodeVisitor_Escaper
Twig_NodeVisitor_Optimizer
Twig_Profiler_NodeVisitor_Profiler
Symfony\Bridge\Twig\NodeVisitor\TranslationNodeVisitor
Symfony\Bridge\Twig\NodeVisitor\TranslationDefaultDomainNodeVisitor
Symfony\Bundle\AsseticBundle\Twig\AsseticNodeVisitor
```

I just recompiled a newer version of php-7 and the performance has gotten a lot better:
```
$ php -version
PHP 5.6.14 (cli) (built: Oct  2 2015 07:11:29) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
$ time ./console cache:clear
Clearing the cache for the dev environment with debug true

real	0m13.234s
user	0m12.737s
sys	0m0.483s
$ ~/misc/php/bin/php -version
PHP 7.0.0-dev (cli) (built: Oct 12 2015 11:38:06) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
$ time ~/misc/php/bin/php ./console cache:clear
Clearing the cache for the dev environment with debug true

real	0m52.256s
user	0m51.607s
sys	0m0.637s
```

The performance for the php 5.6 version changed, because I had xdebug on for the original version.

**Comment by fabpot** [comment] 2015-10-12 10:43
I can confirm:

```
# php-7.0.0
time ./app/console cache:clear
Clearing the cache for the dev environment with debug true
./app/console cache:clear  14.43s user 1.05s system 92% cpu 16.689 total

# php-5.5.17
time ./app/console cache:clear                                                                                     
Clearing the cache for the dev environment with debug true
./app/console cache:clear  5.90s user 0.98s system 91% cpu 7.561 total
```

**Comment by stof** [comment] 2015-10-12 12:57
@fabpot a profiling on PHP would help a lot for that (is blackfire already compatible with PHP 7?)

**Comment by fabpot** [comment] 2015-10-12 12:59
@stof I'm working on that, not sure if I will have time this week as there is SymfonyLive Berlin. But we do have a working Blackfire probe for PHP 7 (not all features are implemented but enough for this use case). I will post my findings here later.

But a simple profile on the PHP 5.x version shows that indeed, most the time is spent in the Twig visitors.

**Comment by stof** [comment] 2015-10-12 14:06
yeah, but being 3 times slower on PHP 7 looks weird

**Comment by austinh** [comment] 2015-10-24 23:48
I can confirm this issue. Also running out of memory on PHP 7 but not on PHP 5.4.

Sometimes get this issue: 

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\OutOfMemoryException' with message 'Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes)' in /var/www/sf2/vendor/twig/twig/lib/Twig/ExpressionParser.php:362
```

**Comment by peteward** [comment] 2015-12-06 12:34
Confirmed here too, did you have any luck with this?

3 minutes here to warm-up my twig cache is a bit prohibitive for us!

AssetManagerCacheWarmer also has slowed down to 50 seconds, although I think this might also use the same Twig loader.

**Comment by peteward** [comment] 2015-12-16 08:54
Anyone had a chance to look at this? 

If only there was a really awesome profiling tool that worked on PHP7 to make life easier here.... :)

**Comment by stof** [comment] 2015-12-16 10:14
@fabpot given that @jpauli has a WIP version of ext-blackfire running on PHP 7, maybe you could try to profile it on PHP 7 to see what causes the slow-down.

**Comment by Tobion** [comment] 2015-12-16 10:58
I cannot really reproduce this on Windows using symfony-standard. (Maybe there are not enough templates though).

```
php --version
PHP 7.0.0 (cli) (built: Dec  3 2015 09:31:54) ( NTS )
time bin/console c:c
real    0m5.803s
user    0m0.000s
sys     0m0.015s
```

```
php --version
PHP 5.6.13 (cli) (built: Sep  3 2015 15:13:31)
time /C/php5/php bin/console c:c
real    0m5.494s
user    0m0.000s
sys     0m0.000s
```

**Comment by peteward** [comment] 2015-12-16 11:31
2 identical Centos 6 VMs (except for one upgraded to php7 with all available extensions via webtatic https://webtatic.com/packages/php70/)

Ours is a heavy project:

```
php --version
PHP 5.6.15 (cli) (built: Oct 31 2015 10:02:09) 

time app/console c:c
real	1m6.781s
user	0m42.172s
sys	0m8.700s
```

```
php --version
PHP 7.0.0 (cli) (built: Dec  2 2015 20:42:32) ( NTS )
time app/console c:c
real	5m7.374s
user	4m43.181s
sys	0m6.106s
```

**Comment by beberlei** [comment] 2015-12-17 19:32
Stumbled across this while preparing to migrate our Symfony Sylius profiling demo app to PHP 7, so I profiled it with [Tideways](https://github.com/tideways/php-profiler-extension) extension using the PHP 7 beta extension and then compared the PHP 5 and PHP 7 output. 

Interestingly what you can see in the comparison is that it is really just `Twig_NodeTraverser::traverseForVisitor` which gets *massively* slower. On every depth of recursion the PHP 7 execution is several seconds slower, leading to a 40 seconds (PHP 5) to 134 seconds (PHP 7) decline.

![](https://tideways.io/assets/content/twig_nodetraverser1.png)

I checked the opcodes that PHP generates for this code using [Derick's VLD](https://github.com/derickr/vld) extension,
but see for yourself - they don't look massively different:

https://gist.github.com/beberlei/768fc8e0a6107868e9eb

Tideways showed me excessive Garbage Collection (99 runs cleaing up thousands of objects) so I tried running both without Garbage Collection, if this was a problem - but performance was still PHP 5 way faster than 7.

So I looked at the Twig code and tried refactoring a little, the following patch fixes the problem:

    diff --git a/lib/Twig/Node.php b/lib/Twig/Node.php
    index 45a8976..0b1b375 100644
    --- a/lib/Twig/Node.php
    +++ b/lib/Twig/Node.php
    @@ -228,4 +228,9 @@ class Twig_Node implements Twig_NodeInterface
         {
             return new ArrayIterator($this->nodes);
         }
    +
    +    public function getChildren()
    +    {
    +        return $this->nodes;
    +    }
     }
    diff --git a/lib/Twig/NodeTraverser.php b/lib/Twig/NodeTraverser.php
    index 00f7b54..ba9fb91 100644
    --- a/lib/Twig/NodeTraverser.php
    +++ b/lib/Twig/NodeTraverser.php
    @@ -76,7 +76,7 @@ class Twig_NodeTraverser
     
             $node = $visitor->enterNode($node, $this->env);
     
    -        foreach ($node as $k => $n) {
    +        foreach ($node->getChildren() as $k => $n) {
                 if (false !== $n = $this->traverseForVisitor($visitor, $n)) {
                     $node->setNode($k, $n);
                 } else {

Interestingly in a trace, you cannot really see *what* makes the `traverseForVisitor` method slow.
The implicit `Twig_Node::getIterator()` caused by `foreach ($node)` was not slow itself. So it shouldn't
actually be a problem in Twig but it looks like a bug in Zend Engine 3.

I was able to easily reproduce this with a small code example in plain PHP, it shows that ArrayIterator()
is broken when you increase the size of the array passed to it:

https://gist.github.com/beberlei/559932c14a9205b00fbe

Starting with an ArrayIterator of size ~10000, iterating over it gets much slower in PHP 7 than in PHP 5.
The larger the array is, the exponentially slower it gets.

ArrayIterator Size | PHP 5    | PHP 7    
------------------ | -------- | --------
1000               | 0.0010   | 0.0009
10000              | 0.0142   | 0.0607
20000              | 0.0284   | 0.5189
65000              | 0.0874   | 5.0322
66000              | 0.0943   | 12.1315
100000             | 0.1399   | 34.8082

The number of Children in a Sylius Twig Cache Warmup Node Traversal is usually much lower, but in total this function is called more than 500.000 times. It adds up with hundrets of small array iterators.

I opened bug report on PHP itself, because I think its a mistake in the new Zend Engine:

https://bugs.php.net/bug.php?id=71153

**Comment by peteward** [comment] 2015-12-17 20:11
wow, great investigation work @beberlei, thank you so much!

Impressive that @nikic has already fixed it.

Looking forward to the next PHP release.

Thank you both!

**Comment by Tobion** [comment] 2015-12-22 15:15
FYI, the PHP fix has not been included in the 7.0.1 release.

**Comment by stof** [comment] 2015-12-22 15:20
Well, this seems logical, as the fix was done after the release

**Comment by Tobion** [comment] 2015-12-22 15:26
Yes that is why we might need to consider adding the workaround from @beberlei depending when the next php patch release is available.

**Comment by jpauli** [comment] 2015-12-22 15:32
7.0.2 is planned for January 7th

**Comment by fabpot** [comment] 2015-12-22 15:33
Closing then.

**Closed by fabpot** 2015-12-22 15:33 UTC

**Comment by peteward** [comment] 2016-01-13 08:25
7.0.2 has indeed sorted out the speed issue, mine now runs through in 17 seconds, however memory consumption around Twig is enormous and considerably more than 5.6.  

It seems like there's still quite a bit of leakage in php7 which is being exposed heavily by something Twig is doing, especially in cache:clear.

I don't have precise numbers to hand now, but in 5.6 clearing cache hasn't been a problem with a memory limit of 128MB, with php7 I was running out of memory at 256MB - it runs through at 512MB.

Has anyone else experienced this or have any ideas to the cause?
