### ISSUE TITLE
Merge does not work when providing numerical array keys

### ISSUE THREAD

**Issue by jin78** [twigphp/Twig#1996] opened 2016-02-24 17:24 UTC
Hi all,

Merge filter does not work when trying to provide numerical array keys.

If the key is 0 or "0", it will NOT be replaced, however if a string array key is used such as "someKey", the actual value matching "someKey" is replaced.

What does not work:
`{% set someVar = someVar|merge({ (key) : someVar.someValue }) %}`

This may be a bug with PHP array_merge function, if so, should it be reported?

**Comment by stof** [comment] 2016-02-25 15:35
It is not a bug of array_merge but a feature. Numeric keys are merged by considering the array as a list.
This is why there is another function named ``array_replace`` in PHP.

**Comment by jin78** [comment] 2016-02-25 23:59
This behavior doesn't seem logical to me. Not to me and I'm not the only one having this opinion.

Is array_replace usable in Twig for numerical indexes?

**Comment by fabpot** [comment] 2016-02-26 04:05
Closing as Twig is just replicating the PHP feature here.

**Closed by fabpot** 2016-02-26 04:05 UTC

**Comment by Tim-arts** [comment] 2018-08-30 10:51
Actually this is a bug because you provide no other option to solve this issue. Expect that every developer having this issue change to string key is not a solution.
