### ISSUE TITLE
attribute() item must be string?

### ISSUE THREAD

**Issue by codefueluk** [twigphp/Twig#2252] opened 2016-11-13 15:23 UTC
Just recently updated to the latest 1.x-dev 827d8e7 build and my attribute() function now breaks as I do a check on the array for an ID.

Seems this is not intended as most Arrays would be ID based for my fix I have had to append '' ~ in front of the ID to enforce a ID as a string for the checks.

My code looks like this. - With my temp fix. 
{% if attribute(hubs, '' ~ hub.id ) %}

**Comment by fabpot** [comment] 2016-11-13 15:29
`hub.id` returns an integer?

**Comment by codefueluk** [comment] 2016-11-13 15:36
That is correct @fabpot, Always returns the ID from the database which is an Auto Increment.

**Comment by fabpot** [comment] 2016-11-13 15:43
Can you provide a minimal test that fails? I've just tried and using an integer on PHP 7 works for me.

**Comment by codefueluk** [comment] 2016-11-13 19:21
@fabpot Will do a few more tests my end, As just entering a Integer it works fine but when being passed from my object it fails.

**Comment by codefueluk** [comment] 2016-11-13 19:50
@fabpot also to note, This is being run on PHP 5.6.16 not 7

It definitely happens on the new update as reverting to my original Twig version (* 1.27.1 (2016-XX-XX)) does it. Seems to be happening when i access a object like object.**2**.value 

Struggling to create a test that breaks outside of my data oddly, Will keep looking.

**Comment by codefueluk** [comment] 2016-11-15 09:48
@fabpot Can't seem to create a test that does it oddly. But noticed that the variables it sometimes does try to fetch don't always exist.

Does seem to be related to the Attribute enhancement commit from what I can tell (bdbfb151115be4eea22e96abd4fd01aa385516aa) as it seems to default to $ret = $object->$method(); for a variable which from what I can tell should only be used when a function is called.

**Comment by fabpot** [comment] 2016-12-13 14:23
@codefueluk Were you able to reproduce this outside of your application?

**Comment by fabpot** [comment] 2016-12-17 21:09
Let's close this one for now. If you find a way to reproduce it, please reopen.

**Closed by fabpot** 2016-12-17 21:09 UTC
