### ISSUE TITLE
[3.9.x] Call to undefined method Twig\Extension\CoreExtension::dateConverter

### ISSUE THREAD

**Issue by Guilain** [twigphp/Twig#4041] opened 2024-04-18 16:36 UTC
Hello

I have this error since the upgrade from 3.8.0 to 3.9.x :
```
An exception has been thrown during the rendering of a template ("Call to undefined method Twig\Extension\CoreExtension::dateConverter()").
```
The line causing this issue is :
```
<p class="text-right email-sales-details-item">{{ sales_entity.expiredAt|format_date }}</p>
```
Content of Twig\Extra\Intl\IntlExtension :
```
... line 370
    public function formatDateTime(Environment $env, $date, ?string $dateFormat = 'medium', ?string $timeFormat = 'medium', string $pattern = '', $timezone = null, string $calendar = 'gregorian', ?string $locale = null): string
    {
        $date = CoreExtension::dateConverter($env, $date, $timezone);
...
```

More infos :
twig/twig is locked at "v3.8.0" cause of "symfony/ux-twig-component" and "symfony/stimulus-bundle"

Best regards,
Guilain

**Comment by stof** [comment] 2024-04-18 16:52
Duplicate of https://github.com/twigphp/Twig/issues/4030

**Closed as not planned** 2024-04-18 16:52 UTC

**Comment by Guilain** [comment] 2024-04-18 17:01
@stof, thanks i missed it...

Adding to temporary "fix" it :
``` json
"conflict": {
    "twig/intl-extra": "v3.9.*"
  },
```
