### ISSUE TITLE
PHP 7+ Support on Twig Extension

### ISSUE THREAD

**Issue by lloy0076** [twigphp/Twig#2110] opened 2016-09-09 14:13 UTC
This has been raised before but if there is no support for PHP 7+ and it's not intended to be supportable can that be, at the least, documented?

Also surely there must be a way to detect which PHP we're building for and the Makefile / configure / m4 macros can say something like "This extension is known not to compile on PHP 7+ - proceed at own risk."

**Comment by alpharder** [comment] 2016-10-18 21:41
👍

**Comment by stof** [comment] 2016-10-19 07:40
@jpauli is there a way to display such message when someone attempts to compile the extension on PHP 7 ?

**Comment by SpacePossum** [comment] 2016-10-20 08:52
Yes, [php.twig.h](https://github.com/twigphp/Twig/blob/1.x/ext/twig/php_twig.h#L20) includes the [php.h](https://github.com/php/php-src/blob/master/main/php.h#L34) file which includes [php_version](https://github.com/php/php-src/blob/master/main/php_version.h) file, so on build this can be tested by the preprocessor (might be useful to test on runtime as well and disable the extension al together?).

**Comment by stof** [comment] 2016-10-20 09:20
@SpacePossum testing on runtime does not make sense, as you cannot reach the runtime (it would require compiling, and the code does not compile on PHP 7)

**Comment by fabpot** [comment] 2016-11-14 04:35
Closing as a duplicate of #1695

**Closed by fabpot** 2016-11-14 04:35 UTC
