### ISSUE TITLE
Math operations with non-numeric strings in PHP8 causes fatal error

### ISSUE THREAD

**Issue by LoranRendel** [twigphp/Twig#3454] opened 2020-12-15 06:57 UTC
In PHP8 conversion of non-numeric string to number is considered fatal error.

Following example will throw a fatal error:

file.php
```php
$twig = new Environment(new FilesystemLoader(__DIR__));
$twig->display('Page.twig', ['test_var' => 'string']);
```

template.html.twig
```twig
{{ test_var + 1 }}
```

Result:
```
Fatal error: Uncaught Error: Unsupported operand types: string + int
in /vendor/twig/twig/src/Environment.php(358) : eval()'d code on line 37
```

**Comment by michaljusiega** [comment] 2020-12-15 07:22
This is expected behaviour since PHP 8.0.
See https://wiki.php.net/rfc/arithmetic_operator_type_checks or https://github.com/php/php-src/pull/5331

**Comment by LoranRendel** [comment] 2020-12-15 08:36
Yes, I know that, but Twig probably should protect from these errors, and it is hard to find source of error by `eval()'d code on line 37`.

**Comment by stof** [comment] 2020-12-15 08:59
Well, adding type checks around each arithmetic operation in compiled twig templates will affect performance for all templates.

Note that if you configure the Twig cache for compiled templates, the compiled templates won't be eval'ed anymore but loaded from the cache folder, which makes the stack trace easier to analyze (as you can open the file in the cache folder to see which template is in it)

**Comment by fabpot** [comment] 2021-01-01 09:34
Closing as I don't think there is anything we can do.

**Closed as completed by fabpot** 2021-01-01 09:34 UTC
