### ISSUE TITLE
Too many User Deprecated: Since twig/twig 3.14: The "Twig\Environment::mergeGlobals" method is deprecated.

### ISSUE THREAD

**Issue by ludekbenedik** [twigphp/Twig#4329] opened 2024-09-20 15:25 UTC
Hi,
we updated Twig to version 3.14.0. Then our deprecation log in Symfony grew to tens GB during a few hours. The Twig\Environment::mergeGlobals method is called in Twig library so we cannot solve this deprecation. We have disabled the deprecation logging for this moment.

Is it necessary for the library to use this own deprecated function?

Thank you

**Comment by stof** [comment] 2024-09-20 15:29
Twig does not use it anymore.

however, the form rendering in `symfony/twig-bridge` still uses it (the usage has been replaced in Symfony but the change is not released yet)

**Comment by xabbuh** [comment] 2024-09-20 15:29
This is probably caused by the installed version of the `symfony/twig-bridge` package. Its next patch release will fix it. In the meantime you can use the dev version of the upcoming patch release (see symfony/symfony#58219).

**Comment by ludekbenedik** [comment] 2024-09-20 15:34
You right, problem is here `Symfony\Bridge\Twig\Form\TwigRendererEngine`.

I am sorry.

**Comment by fabpot** [comment] 2024-09-20 16:04
Closing as I will release Symfony soon.

**Closed as completed by fabpot** 2024-09-20 16:04 UTC

**Comment by xabbuh** [comment] 2024-09-21 06:21
@ludekbenedik FYI, you can update the Twig bridge now.
