### ISSUE TITLE
Incompatibility with Assetic bundle

### ISSUE THREAD

**Issue by openlife** [twigphp/Twig#2890] opened 2019-03-12 14:48 UTC
Today update from 2.6.2 to 2.7.0 generate fatal error for incompatibility with Assetic

Compile Error: Declaration of Assetic\Extension\Twig\AsseticTokenParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $to  
  ken)

**Comment by xabbuh** [comment] 2019-03-12 15:00
see #2886

**Comment by stof** [comment] 2019-03-12 15:01
Duplicate of #2886

**Comment by ricbra** [comment] 2019-03-12 15:02
Same here, and reverting is not an options because of the CVE released today: https://symfony.com/blog/twig-sandbox-information-disclosure

**Comment by stof** [comment] 2019-03-12 15:12
@ricbra the fix is already in progress.

And the CVE only affects you if you are using the sandbox (and it affects you since you started using it)

**Comment by fabpot** [comment] 2019-03-12 15:49
fixed in 1.38.1 and 2.7.1 (which I've just released).

**Closed as completed by fabpot** 2019-03-12 15:49 UTC
