### ISSUE TITLE
Issues with Twig_Template::getSource()

### ISSUE THREAD

**Issue by javiereguiluz** [twigphp/Twig#2011] opened 2016-04-01 10:13 UTC
How to reproduce:

  * Install the Symfony Demo app (`$ symfony demo`)
  * Browse any page (e.g. `/en/blog/`)
  * Click on the `Show code` button
  * **ERROR** Twig code is empty
  * Reload the page and click again on the `Show code` button
  * **FIXED** Twig code is displayed

@stof thinks this is caused *"because Twig does not load the cache file but evals the code when the cache does not exist yet"*. More details: https://github.com/symfony/symfony-demo/issues/224

**Comment by javiereguiluz** [comment] 2016-06-27 15:21
Since this bug is still happening in the Symfony Demo application, we added a workaround for it: https://github.com/symfony/symfony-demo/pull/356/files  I don't know if this could help Twig solve this error, but it solved the problem for us.

**Comment by fabpot** [comment] 2016-09-20 05:31
#2129 should fix this issue.

**Comment by fabpot** [comment] 2016-09-20 18:15
@javiereguiluz Can you check that the issue is fixed now? The workaround in the demo should not be needed anymore as `getSource()` is now always defined (at least as of 1.25 :)).

**Closed** 2016-09-20 18:14 UTC

**Comment by javiereguiluz** [comment] 2016-09-29 13:36
I finally could test this and it solved our problems. Thanks!  Details: https://github.com/symfony/symfony-demo/pull/382
