### ISSUE TITLE
passing variables between blocks

### ISSUE THREAD

**Issue by kitsguru** [twigphp/Twig#1479] opened 2014-08-16 23:23 UTC
The documentation states that variables are scoped in a for loop but does not specify the scope within or between blocks.
I would expect that t3 and tlast should be 2 in the following example, however that is not the case. 
````
        {% set text = 0 %}
        t0: {{ text }} <br>
        {% block t1 %}
            {% set text = 1 %}
            t1 {{ text }} <br>
        {% endblock %}
        {% block t2 %}
            {% set text = 2 %}
            t2 {{ text }} <br>
        {% endblock %}
        {% block t3 %}
            t3 {{ text }} <br>
        {% endblock %}
        tlast {{ text }} <br>
````
produces the following output:
t0: 0
t1 1
t2 2
t3 0
tlast 0 

How can I pass the value of a variable from one block to another? 
i.e. so in the above example t3 is 2

**Comment by Koc** [comment] 2015-06-22 12:11
seems to be duplicate of #1302

**Closed** 2015-09-06 07:00 UTC

**Comment by brooksvb** [comment] 2017-11-25 07:06
I don't see how this is a duplicate of #1302. How should the above twig be written if you want t3 and tlast to show "2"?
